name: Terraform Deployment

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your repository code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # Action to set up Terraform CLI
        with:
          terraform_version: 1.0.0  # Replace with your desired Terraform version

      - name: Initialize Terraform
        run: terraform init -input=false  # Initialize Terraform with auto-approve

      - name: Plan Terraform
        run: terraform plan -out=tfplan -input=false  # Generate Terraform plan

      - name: Apply Terraform
        run: terraform apply -input=false tfplan  # Apply Terraform changes

      - name: Validate Terraform
        run: terraform validate  # Validate Terraform configuration syntax